POST http://localhost:3000/auth/users/signup
Content-Type: application/json

{
    "username": "beza",
    "email": "beza@gmail.com",
    "password": "beza123",
    "role": "admin"
}

###
PUT http://localhost:3000/api/admin/update/:_id
Content-Type: application/json 

{  
    "description":"Very bad",
    "address":"Asamara",
    "maxGuest":"7",
    "bedRoom":6,
    "bathRoom":2,
    "offer":["Air Conditioning","Parking Lot"],
    "checkinType":"Assisted CheckIn",
    "picture":"picture",
    "price":"67"}
    //"__v":0}

###
GET http://localhost:3000/api/admin/houses